server:
  port: 8080
  servlet:
    context-path: /pcs-master
app:
  env: local
  component: pcs-master
  module-name: PCS

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: penta
    password: penta
    url: jdbc:mysql://localhost:3306/scs_okame

#http://localhost:8081/pcs-master/swagger/swagger-ui/index.html?configUrl=/pcs-master/swagger/api-docs/swagger-config
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    operationsSorter: method

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

jwt:
  secret: pentasol@okame!
  expire: 720